### ISSUE TITLE
Сортирането по Високо оценени добавя допълнителен резултат

### ISSUE THREAD

**Issue by svetlik** [obshtestvo/signali#18]
http://demo.signali.bg/contact-points/?areas=41&sorting=-rating&start=0
1. Виж броя резултати (34)
2. Отиди на Подреди местата по
3. Избери Високо оценени

Реален резултат: бройката се увеличава с един (35)

**Comment by antitoxic** [comment]
Дано това е свързано с https://github.com/obshtestvo/signali/issues/15, че иначе ще падне много debugg-ване

**Comment by yuleto** [comment]
Потвърждавам и допълвам - при зададени различни критерии, сортирането по Високо оценени понякога добавя не един, а три резултата (може да се възпроизведе от страницата с пълния списък на местата без зададен критерий demo.signali.bg/contact-points/)

**Comment by antitoxic** [comment]
В работата по https://github.com/obshtestvo/signali/issues/52 реших и този проблем. Скоро ще обновя демото онлайн.
