### ISSUE TITLE
Неработещи линкове

### ISSUE THREAD

**Issue by svetlik** [obshtestvo/signali#19]
Линковете във футъра под "За Signali.bg" не работят
(work in progress?)
- "Какво е Signali.bg" - изкарва страница с текст "generic: No Page matches the given query."
- За BlueLink и За Общество.бг не водят никъде

![screen shot 2015-09-12 at 7 21 48 pm](https://cloud.githubusercontent.com/assets/1100307/9832437/8845e4e8-5983-11e5-8841-eaf5ee198e11.png)

**Comment by antitoxic** [comment]
Related  to https://github.com/obshtestvo/signali-theme/issues/16 .
