### ISSUE TITLE
Loader анимацията се появява след всеки тип линк (mailto, външна страница), а трябва да се появява само за вътрешни линкове

### ISSUE THREAD

**Issue by svetlik** [obshtestvo/signali#20]
http://demo.signali.bg/contact-points/asotsiatsiia-demetra-burgas/#feedback
1. Добави още една оценка на място, за което вече си писал как е минало
2. Появява се следното съобщение; кликни върху мейл адреса info@signali.bg
   ![screen shot 2015-09-12 at 7 32 27 pm](https://cloud.githubusercontent.com/assets/1100307/9832497/0a8493ea-5985-11e5-8557-af4a115b71e6.png)
3. Отваря се прозорец на Mail app, в който въвеждаш (или не) съобщение
4. Затвори прозореца на Mail app

Реален резултат: Страницата стои заредена, но се вижда единствено:
![screen shot 2015-09-12 at 7 35 14 pm](https://cloud.githubusercontent.com/assets/1100307/9832512/68bf90ae-5985-11e5-83e2-0d2d5edafaa1.png)

Забележки: 
- оправя се при обновяване на страницата

**Comment by antitoxic** [comment]
Сещам се какво е това. В момента сайта щом усети кликане на друг УРЛ от текущия на страницата пуска анимацията за зареждането. Ще го оправя.
