### ISSUE TITLE
Мобилен сайт: Съобщението "Оценката ти очаква модерация" се появява за място, на което потребителят все още няма оценки.

### ISSUE THREAD

**Issue by svetlik** [obshtestvo/signali#22]
http://demo.signali.bg/contact-points/agentsiia-po-vpisvaniiata/#feedback
1. Отвори мобилния сайт
2. Отиди на място, където все още нямаш коментар
3. Напиши как мина, но не пропусни да дадеш оценка със звездички
4. Дай оценка със звездички и отговори на двата въпроса
5. Изпрати оценката

Реален резултат: Излиза съобщението "Оценката ти очаква модерация"

![img_2756](https://cloud.githubusercontent.com/assets/1100307/9832622/965dddd2-5989-11e5-93af-8d9dba5a2f43.png)

**Comment by antitoxic** [comment]
Closed via https://github.com/obshtestvo/signali-theme/commit/815001884ca0cad47143e812795bba1e737ff8a1

Мерси! И ако пак видиш да се появява проблема казвай

**Comment by antitoxic** [comment]
- Hard-refresh преди това нови проверки :smiley:
