### ISSUE TITLE
Правописни грешки

### ISSUE THREAD

**Issue by svetlik** [obshtestvo/signali#23]
http://demo.signali.bg/contact-pointsagentsiia-ptna-infrastruktura/
- Тоята оценка за „Агенция пътна инфраструктура“ -> Твоята
- Не изисква адресът ти -> Не изисква адреса ти
- Гараниран отговор -> Гарантиран

http://demo.signali.bg/ -> "Добави място"
- Ако знаеш за място в интернет, от където може да се подаде сигнал, кажи за него: -> откъдето
- Разкажи за ограничения в видовете приемани сигнали, специфики или инструкции при подаването.  -> във видовете

**Comment by antitoxic** [comment]
Closed via https://github.com/obshtestvo/signali-theme/commit/5884866ba9b00feb08028364e5a92c0253e79057

Благодарско!
