### ISSUE TITLE
Profile update details

### ISSUE THREAD

**Issue by marianbida** [obshtestvo/signali#24]
1. При опресняване на паролата няма валидация
2. При опресняване на името и емаил адрес няма валидация.

**Comment by antitoxic** [comment]
Какво точно няма? Под какъв браузър? При мен има и за двете. На няколко места съм тествал
![2015-09-13_08-44-47](https://cloud.githubusercontent.com/assets/261500/9835436/b4d83d74-59f3-11e5-8dcf-3ea0dd7ea792.png)

**Comment by antitoxic** [comment]
Затварям, понеже не можах да пресъздам, а може да е оправено в процеса на работа.
