### ISSUE TITLE
Facebook логин

### ISSUE THREAD

**Issue by marianbida** [obshtestvo/signali#26]
1. При логин с facebook казва че url-to не е добавено в allow domain
   http://prntscr.com/8fk1aj

**Comment by yuleto** [comment]
Потвърждавам, че горната грешка се появява при опит за логин с фб, но само когато съм в страницата на някоя институция (както е примерът в скрийншота).

Когато съм на главната страница demo.signali.bg (дори след филтриране на категории) успявам да се логна с фб. Ако обаче натисна cancel, формата забива на пулсираща точка и трябва да презаредя страницата, за да се оправи.

**Comment by antitoxic** [comment]
Някой има ли опит с такива проблеми с Facebook? Пробвах какво ли не. Все още излиза тази грешка.
![2015-10-11_09-29-02](https://cloud.githubusercontent.com/assets/261500/10415259/b138fb64-6ffa-11e5-83e2-fa73a9783cfe.png)

@marianbida ?
