### ISSUE TITLE
Странни фрази

### ISSUE THREAD

**Issue by marianbida** [obshtestvo/signali#27]
1. "КАЖИ КАК МИНА" - малко ми е странно това, обръщението на ти в публични сайтове, сякащ все още е странно, особенно за по начетени хора.
2. Местност, в която се е случило, там имаме градове и области, те не са местности, не е грешка, просто не е някакси на български.
   http://prntscr.com/8fk37g
3. "ЗА КАКВО СЕ ОТНАСЯ" не може ли да е просто "относно"
4. "Колко сте доволни от подаването на сигнала?" - вобще не мога да разбера какво ме питат, оценка на сигнала ли е, на моя сигнал ли е, на некой друг сигнал ли е, не е ясно.
5. "Начална страница" -> "Начало"

**Comment by antitoxic** [comment]
1. Защо странно? Контрастира с отдалечаващите "Вие" сайтовете на администрацията.
2. Това е опит за дума, която обхваща градове, села, области. Не знам по-добора. Ти имаш ли предлжение?
3. Относно, отново е много формално, опитваме се да е по-достъпно с думи
4. Това което се пита е "Щом си в секцията, "твоята оценка", значи вече си подавал сигнал към даденото място. Как е минало подаването" . Със сигурност не е най-добрия въпрос. Ти как би го оформил?
5. Начална страница е много по-ясно от Начало. Затова ще е запазим така.

**Comment by antitoxic** [comment]
Свързано с https://github.com/obshtestvo/signali/issues/34
