### ISSUE TITLE
Дизайн

### ISSUE THREAD

**Issue by marianbida** [obshtestvo/signali#28]
1.Огромни празни места в шапката, не знам така ли треба да е, но все очаквам да има нещо там, но няма нищо, празно.
http://prntscr.com/8fk55e
2. Вместо "снимка" -> "изображение" -> http://prntscr.com/8fk5tz
3. Пречките са: -празно-, или го махнете или напишете няма посочени пречки и/или препятствия или затруднения.
http://prntscr.com/8fk6bs

**Comment by antitoxic** [comment]
1) и 2) така е замислено да бъде. Има смисъл зад двете.

3) - да това е проблем, ще оправя идната седмица
