### ISSUE TITLE
Няма софия в тъсачката за място, страницата се презарежда без да филтрира.

### ISSUE THREAD

**Issue by Stanislav** [obshtestvo/signali#32]
София я няма в търсачката за местоположения.

Натискане на ентър за свободно написан текст, който не фигурира във списъка със зададените градове - презарежда цялата страница.

Тук натискам ентър около 1-2 секунди след като приключвам с писането на "софия". Резултатите са някакви произволни:
![2015-09-14_23-19-55](https://cloud.githubusercontent.com/assets/2486389/9861248/cfb3547a-5b39-11e5-9f79-a06f861cc01c.gif)

Надявам се не съм се заблудил и това, че София я няма, не е нещо нарочно. Презареждането на страницата обаче не трябва да става ако не са намерени резултати, според мен.

**Comment by panev** [comment]
Реално съществува като "Столична" понеже са общини, което не става ясно веднага и създава обърквация. 

Може просто да си е София и в скобите да е (Столична Община) за да улесни търсенето.

**Comment by antitoxic** [comment]
Да ще се добави.  @panev ти натискаш ли ентер преди да зареди?

**Comment by panev** [comment]
@antitoxic Натискам tab, виж #42. Enter натискам след като съм попълнил и второто поле, с идеята да активирам търсенето. But that's just me :)
