### ISSUE TITLE
Две преповтарящи се опции от "Какво предлага мястото"

### ISSUE THREAD

**Issue by Stanislav** [obshtestvo/signali#33]
![verification](https://cloud.githubusercontent.com/assets/2486389/9861439/0a0692b2-5b3b-11e5-9c6e-439765a73fc3.png)

Когато се създава ново място под секцията "какво предлага мястото" има две опции:
"Верификация на сигнала" и "Потвърждаване на сигнала". 

Мисля че "Потвърждаване на сигнала" трябва да остане.

Мисля че това са едно и също нещо. Може би верификация на сигнала е чуждицата която е била заместена с българската алтернатива по-късно, но и старото е останало.

**Comment by yuleto** [comment]
Допълнение: дублирането го има и при допълнителните опции във формата за търсене:

![screen shot 2015-09-18 at 1 36 56 am](https://cloud.githubusercontent.com/assets/14294309/9947831/0bacc196-5da6-11e5-8dbc-8ddc335134bf.png)

**Comment by antitoxic** [comment]
Това са различни неща. Трябва обаче перафразиране. 

Потвърждаване на сигнала е - Институцията ти потвърждава че е приела самия сигнал.
Верификация на сигнала - можеш да провериш какво става със сигнала (status check).

По дизайна ще се опитаме да добавим и "(?)" символ след всяка отметка за да може дповече информация за нея да има.

**Comment by Dreamture** [comment]
Добавих стил за подсказка. Ето превю:
![addsignal](https://cloud.githubusercontent.com/assets/4492376/11392629/aff90f96-9363-11e5-9453-a1897b4b83c9.jpg)
