### ISSUE TITLE
Стилистични забележки

### ISSUE THREAD

**Issue by yuleto** [obshtestvo/signali#34]
1. Има нужда от редакция на различни места (липсващи запетайки, тирета, изпуснати букви, странен словоред). Предвидено ли е да се редактира? Ако има текстови файлове, бих могла да ги погледна, със скрийншоти ще ми е трудно.
2. Би било добре да се уеднакви/ опрости изказът във формата за търсене:
   a) "Къде се е случило" вместо "Местност, в която се е случило" (така пасва по-добре със "За какво се отнася")
   b) описанието в полето "За какво се отнася" ми се струва твърде многословно, "Търси по ключови думи" примерно ми звучи по-удачно. Като потребител малко се обърквам от разделянето на "категории" и "теми", че и "директни съвпадения" излизат понякога...
   c) "Не изисква име" вместо "Не изисква името ти"
   d) "Не изисква адрес" вместо "Не изисква адреса ти"
   *Според мен и без уточнението с "ти" е ясно, че става въпрос за лични данни, предвид другите опции. Ако се опасявате от объркване, може да е нещо като "име/адрес на подателя". 
   e) под всеки резултат - "Подай сигнал" вместо "Подаване на сигнал"

P.S. По принцип натрапчивата фамилиарност не ми допада особено. Като портал за връзка с официални институции ми се струва, че сайтът е добре да поддържа някакво ниво на формалност. Нямам предвид да е на "Вие",  просто да не звучи все едно сме се заговорили на улицата:) Примерно "Кажи как мина" може да се замени с "Остави/ Изпрати отзив" или нещо подобно. И разбира се, на каквото и да се спрете като стил, добре е да не се смесват, както се е случило в полето за оценка на място:

Твоята оценка за „"Главна Дирекция "Гранична полиция"“
и директно отдолу:
Колко сте доволни от подаването на сигнала?

**Comment by antitoxic** [comment]
Много яки забележки, @yuleto !

Оправихме някой от тях:
- "Къде се е случило" и "Какви категории и ключови думи описват проблема"
- "кажи как мина" вече е "сподели опит"
- "място за сигнал"  вече е "сайт"
- "област" вече е "място" - тук може би е по-добре да е "регион"?

Можеш да правиш предложения за редакции [започвайки от страницата за търсене в проекта](https://github.com/obshtestvo/signali-theme/search) по следния начин:
![2015-12-02_11-02-26](https://cloud.githubusercontent.com/assets/261500/11526609/4472b674-98e4-11e5-9a8c-139216e27788.gif)

Когато натиснеш моливчето ще създадеш копие на проекта в твоя акаунт и ще можеш да правиш промени там. Като свършиш с промените можеш:
1. Да пратиш линк към твоето копие
2. Да направиш  "pull request"

Както ти е най-удобно.

**Comment by antitoxic** [comment]
"Не изисква име" и "Не изисква адреса ти" се запазват, понеже без "ти" може да се разбере като "име" на човек срещу който се подава сигнал или "адрес" на който се е случил проблема.

"Подай сигнал" не може да го сменим понеже реално линк не води към страница, където може да подадеш сигнал, а към страница с детайли за процеса по "подаване на сигнал"
