### ISSUE TITLE
Oбъркващ текст в изскачащия прозорец "Преди да публикуваме"

### ISSUE THREAD

**Issue by yuleto** [obshtestvo/signali#35]
Без да си се логнал -> отиваш в страницата на някое място -> даваш оценка, попълваш "кажи как мина" -> натискаш "изпрати", изскача прозорец  "Преди да публикуваме". Следва текст "Регистрирай се..." - ако е без профил, човек може да реши, че е форма за регистрация. По-добре "Влез в профила си или се регистрирай" със съответните линкове... Или да излиза направо формата за регистрация (при нея има и линк за вход).

Също така, бутонът "направи си регистрация" не е достатъчно видим (синьото почти се слива с полупрозрачния син фон). 

![screen shot 2015-09-18 at 12 13 41 am](https://cloud.githubusercontent.com/assets/14294309/9947247/5e594ebe-5da1-11e5-95d4-2bdab700155b.png)

По-добре да изглежда така:

![screen shot 2015-09-18 at 12 14 16 am](https://cloud.githubusercontent.com/assets/14294309/9947261/85f7bab4-5da1-11e5-95b6-62754650e344.png)

Тествано на Chrome (Windows/OSX)

**Comment by Dreamture** [comment]
Предлагам варианти за бутона "Направи си регистрация" - http://sht.tl/FBdynx

По въпроса с wordinga, моето мнение е, че може би наистина трябва да обърнем входа с регистрация, т.к. презумпцията ми е, че нямаме много голям user base и по-скоро, и че на хората ще им трябва регистрация. Единствено бих добавил същия голям бутон отдолу, който да води към "Вход"

**Comment by antitoxic** [comment]
@Dreamture дай други варианти. Първия е тотално обратното на забележим, едвам се вижда, като footer седи. Втория пак не изглежда на бутон, а прилична на прекалено ярко каре.

и + Fontawesome иконката за user е гадничка, и не знам защо имаме иконка за user на регистрация, но на вход не.

Може да обърнем вход и регистрация, това не е проблем.

**Comment by Dreamture** [comment]
Редизайн на Вход. Нека да сменим първоначално да изкарваме Регистрацията като при нея дизайна ще е същия, но просто ще оставим и сегашното "или вход" до бутона "Регистрация"
![login register](https://cloud.githubusercontent.com/assets/4492376/11503263/63e84f74-9848-11e5-9a6f-0043c99cbde6.jpg)
