### ISSUE TITLE
Объркващи елементи във формата за търсене

### ISSUE THREAD

**Issue by yuleto** [obshtestvo/signali#36]
Допълнителните опции не се виждат след търсенето, когато нещо е чекнато; добре е да се виждат.
Не се разбира по кои критерии точно съвпадат резултатите, само бройката е видима. Проблем е, когато се зададат повече критерии, а намерените резултати съвпадат само по някои от тях.

Тук съм задала допълнителни опции:
![screen shot 2015-09-18 at 12 18 12 am](https://cloud.githubusercontent.com/assets/14294309/9947323/fb8cb04a-5da1-11e5-88a9-990e1b534d8f.png)

След търсенето са се сгънали, все едно, че нищо няма зададено.
Също така са зададени 9 критерия. Най-добрите резултати съвпадат само по 6 критерия, но не се знае точно кои са.

![screen shot 2015-09-18 at 12 18 42 am](https://cloud.githubusercontent.com/assets/14294309/9947345/13df6886-5da2-11e5-9ff4-da8824db24a4.png)

Тествано на Chrome (Windows/OSX)

**Comment by Dreamture** [comment]
Моля вижте - https://github.com/obshtestvo/signali/issues/44
