### ISSUE TITLE
Объркващи елементи във формата за добавяне на място

### ISSUE THREAD

**Issue by yuleto** [obshtestvo/signali#37]
1.Добави място -> избиране на категория - няма достатъчно ключови думи като при формата за търсене. Примерно няма Дискриминация (само "Директно съвпадение" излиза) 
1. Добави място -> избиране на регион - добре би било "Национален" да е най-отгоре.

**Comment by antitoxic** [comment]
Полето "Категория" е само за категории при добавяне, където главната търсчка включва категроии, тагове и директно търсене в имената на местата за подаване на сигнал.

 Ти би искала да има още едно поле при добавяне - за въвеждане на тагове?
