### ISSUE TITLE
Пренасочване - различно поведение според това дали си се логнал

### ISSUE THREAD

**Issue by yuleto** [obshtestvo/signali#38]
Ако не си се логнал, когато от страницата на мястото отидеш "към мястото", изскача прозорец за пренасочване и възможност за напомняне по имейл.
Когато си се логнал, такъв прозорец не изскача, а директно си пренасочен. Това означава ли, че автоматично е активирано напомнянето по имейл? Може би е добре да съществува като опция, или поне да има информиращо съобщение, че ще ти бъдат изпращани напомнящи ймеили.

Тествано на Chrome (Windows/OSX) и Safari iOS 8.3

**Comment by antitoxic** [comment]
Да, автоматично е активирано.

Създавам ново "issue" #50 по въпроса с индикация за автоматичните припомняния. Затварям това.

Благодаря!
