### ISSUE TITLE
Мобилна версия - твърде трудно излизане от профила

### ISSUE THREAD

**Issue by yuleto** [obshtestvo/signali#39]
Когато натисна снимката/ стрелката до снимката, за да се появи менюто с "изход", ми изскача прозорец с опции за настройки на профила и не мога да изляза. Веднъж на десет пъти успявам да натисна само стрелката и да изкарам само менюто. На десктоп менюто излиза при ховър с мишката и този проблем го няма.

Тествано на Safari, iOS 8.3, iPad

**Comment by Dreamture** [comment]
@antitoxic просто като натиснеш снимката не трябва да се отваря прозореца. Тогава просто ще излиза менюто с двата линка "Настройки" и "Изход"
