### ISSUE TITLE
Объркващо изпращане на отзив за дадено място

### ISSUE THREAD

**Issue by yuleto** [obshtestvo/signali#40]
Когато си логнат:
Ако не си дал оценка със звездички, а въведеш само текст, нищо не се случва, когато натиснеш "изпрати" (само полето за текст позеленява).
След няколко натискания цъкнах на звздичките, чак тогава се разпънаха другите две опции за гласуване и видях, че всъщност са задължителни полета и затова не се е пратил отзивът. 

Тествано на Chrome (OSX) и Safari iOS 8.3

**Comment by antitoxic** [comment]
Оправено.
