### ISSUE TITLE
Нелогични линкове, неработещи тагове

### ISSUE THREAD

**Issue by yuleto** [obshtestvo/signali#41]
На страницата на конкретно място:
Изброените предимства и недостатъци по някаква причина са линкове, водещи към същата страница, на която си в момента.
Таговете не водят наникъде.

На скрийншота не се вижда, но като ховърнеш над текста, стрелката става на ръчичка.
![screen shot 2015-09-18 at 12 24 47 am](https://cloud.githubusercontent.com/assets/14294309/9947715/194baee4-5da5-11e5-93e2-637381d69d22.png)

Тествано на Chrome (OSX)

**Comment by antitoxic** [comment]
Оправено.
