### ISSUE TITLE
[UX] Подобрение в навигацията с клавиатура е в търсенето

### ISSUE THREAD

**Issue by panev** [obshtestvo/signali#42]
![2015-09-18_17-37-28](https://cloud.githubusercontent.com/assets/3509489/9962039/6d7f5772-5e2c-11e5-99cc-435b31a059e8.gif)

Натискайки Tab когато си в полето "Местност" изчиства текста, вместо да го запазва. (Дори да си написал пълният резултат.

Натискайки Enter го въвежда, но не отива на следващото поле.

Би било по-приятно за потребителя след като е написал например "Пло", и първият резултат е "Пловдив", когато натисне Tab, да се въвежда резултата в полето и да се отива на следващото.

Представлява и пречка, понеже трудно се забелязва, че не се е въвело заради placeholder-а.

**Comment by Dreamture** [comment]
Това тук е доста спорно според мен. Не мога да се сетя за пример (app/website), в който да работи така макар и на мен много пъти да ми се е искало да работи точно така, но ние сме power users. 

По-скоро бих го направил при написано нещо и натискане на Таб да ти сменя опциите отдолу и при Enter да те праща на следващото поле. Ако е една просто няма да ти сменя нищо, но няма да ти позволява и да отидеш на следващото поле. За справка вижте Chrome address bar-a

Иначе съм дал препоръки/корекции за стила на самия placeholder.

**Comment by panev** [comment]
Според мен, проблемът конкретно е, че полето се чисти и губиш това което си написал, когато натиснеш Tab (каквото и да очакваш да се случи когато го правиш). Влошава се когато placeholder-a прилича на истински текст, понеже може да не забележиш, че се е изчистило.

Напълно съм съгласен, че не се вписвам в повечето персони, които ще ползват това нещо (въпреки, че бих го ползвал редовно!). Може би трябваше да напиша "...по приятно за мен" вместо "...по-приятно за потребителя".

Решението Tab да навигира из списъка, а Enter да въвежда стойност и сменя полето също би работило по-добре, от текущото състояние.

**Comment by antitoxic** [comment]
Вече се добавя избрания резулат, когато се натисне <kbd>TAB</kbd>. 

Сега това issue се променя на следното: Трябва само когато е написан текст да се избирара първия резултат - в момента <kbd>TAB</kbd> избира резултата дори и да няма написан текст, което при голямата търсачка (категории и ключови думи) създава безкрайно избиране на първия резултат.

**Comment by antitoxic** [comment]
Готово
