### ISSUE TITLE
[UX] Нерелевантни и объркващи резултати при търсене

### ISSUE THREAD

**Issue by panev** [obshtestvo/signali#43]
При търсене изглежда, че ако не се намери място за подаване на сигнал по двата критерия ("Местност" и "За какво се отнася") ти връща всички места за подаване на сигнал само по Местност:

![2015-09-18_17-53-09](https://cloud.githubusercontent.com/assets/3509489/9962385/2afd2c74-5e2e-11e5-878c-88680e0243c1.png)

Не се сещам за сценарии в който човек би искал да подаде какъвто и да е сигнал в определена местност. Представям си нуждите малко по-конкретни. 

Проблемът се задълбочава, понеже етикетът, който ти казва, че това са всякакви места които приемат сигнали в определена местност е доста незабележим. Няма индикатор, който казва на потребителя, че няма намерени резултати по двата критерия и се показват само по единият. Става ясно само когато си търсил например "Бракониерство" в "Пловдив" и резултатите нямат нищо общо. Това кара системата да изглежда повредена и ненадеждна.

Когато има намерени резултати се получава нещо подобно, понеже понякога са равен брой и се смесват, което повтаря объркването.

Моето предложение да има доста по-ясна индикация, че няма намерени резултати по двата критерия. Не съм много сигурен и каква е ползата от изброяването на всички места приемащи сигнали в дадена местност. По-скоро трябва да е обратното—ако няма място за подаване на сигнал за "Бракониерство" в "Област Пловдив", може да се изкарват областите в които има. Но отново за това трябва да има ясна индикация. Наистина мисля, че етикетът в момента е недостатъчен.

**Comment by Dreamture** [comment]
С Тони поработихме и стигнахме до това като вариант. Какво мислите? Идеята е, че максимално запазваме layout-а на търсачката на началната страница и в същото време изглежда доста по-компактно (за да спестим височина).
![listing-v2-expanded](https://cloud.githubusercontent.com/assets/4492376/11500695/66868950-9837-11e5-95f0-c264acdd329c.jpg)
![listing-v2](https://cloud.githubusercontent.com/assets/4492376/11500694/66857858-9837-11e5-8d55-47ed1ac12298.jpg)
