### ISSUE TITLE
Прекалено много скрол за страницата с резултати

### ISSUE THREAD

**Issue by antitoxic** [obshtestvo/signali#44]
Листинг страниццата (след търсене) има прекалено много скрол докато се стигне до резултатите. Има много пространство в хедъра, а и търачката извзема прекалено много площ.

Може би ни трябва вкарване на цялата търсачка и филтри в 1 поле което реално не е интерактивно, а просто е рецензия и прилича на инпут (но не е) и като се кликне се появяват всички филтри. 

Предния абзац може да обърква. Ако дизайнера го чете да ми звънне :)

**Comment by Dreamture** [comment]
@antitoxic намалих височината на сърча след като качих бутона горе, обединих филтрите в една група, която си мисля, че е ОК да е скрита по дефолт. Изчисти филтри се появява само при първия чекнат филтър.

Също така намалих височината на хедъра от 390px на 300px

Сега гледам, че по първоначално по дизайн съм поддал в сепарратора между отделните кутийки да пишем, резултатите кои филтри включват - http://sht.tl/mwncwE

![listing](https://cloud.githubusercontent.com/assets/4492376/11396038/6bd0d6f0-9377-11e5-9900-e5b9372e34d3.jpg)

**Comment by antitoxic** [comment]
@Dreamture 

> Сега гледам, че по първоначално по дизайн съм поддал в сепарратора между отделните кутийки да пишем, резултатите кои филтри включват - http://sht.tl/mwncwE

Това не разбрах каква връзка има?

Все още е прекалено високо. Виж какво може да преоразмериш като текстове и подреждане в header-a. Ако помниш говорихме да се помисли за по-хитър начин за смаляване на височината, не просто отстояния. Говорехме че може да има бутон "филтри" както при мобилните апове, като до него може да пише само с текст какъв филтър е актвиран. Може и да има бутон "редактирай филтри". Или пък може и да има само иконка за филтър (фуния) с маркер (нещо като червеното кръгче с notification броя на iphone).

Помниш ли? Би ли направил такъв вариант?

**Comment by Dreamture** [comment]
Ето до тук стигнахме с тази страница.
![listing-v2](https://cloud.githubusercontent.com/assets/4492376/11502112/9640e5aa-9841-11e5-9f7d-99f1480953ff.jpg)
![listing-v2-expanded](https://cloud.githubusercontent.com/assets/4492376/11502113/965c0f24-9841-11e5-8998-017f85f85702.jpg)
