### ISSUE TITLE
Думата "място"  се бърка с географско "място"

### ISSUE THREAD

**Issue by antitoxic** [obshtestvo/signali#45]
Трябва нова фраза за "място за подаване на сигнал"

Засяга особено action button-и като "Добави място" .

В краен случай ще стане "Добави ново място, където се подават сигнали", но по това трябва да се помисли за ефекта в/у дизайна.

**Comment by Dreamture** [comment]
Така е "място" от самото начало ми звучи доста generic. 
"организация", "институция" (тук обаче изключваме някои категории" ми звучат доста по-добре

Иначе толкова дълъг бутон е немислимо :))

**Comment by antitoxic** [comment]
"Място" става на "сайт". 

Географско място, от "област" става на "местонахождение" или "място" в зависимост от контекста.
