### ISSUE TITLE
Хората не разбират защо им предлагаме да дават рейтинг

### ISSUE THREAD

**Issue by antitoxic** [obshtestvo/signali#47]
Трябва по-видим да е текста и може би винаги да включва: "Ако сте имали опит с подаване на сигнал към "Име На Институция" --->>> споделете го

**Comment by Dreamture** [comment]
@antitoxic , мисля че го направих малко по-intrusive. Като институцията съм я направил да е линк. Стиловете ги имаш. 
![screen shot 2015-11-25 at 11 17 48](https://cloud.githubusercontent.com/assets/4492376/11393046/2e175930-9366-11e5-9838-7793bf707c93.png)

**Comment by Dreamture** [comment]
Попроменихме малко частта с даването на коментар. + в този скрийн е показан вариант на профил, в който можеш да пуснеш сигнал само по само да пуснеш мейл
![profile-mail](https://cloud.githubusercontent.com/assets/4492376/11502227/300ae37a-9842-11e5-9b74-4eea50dd7e74.jpg)
